# Generated by Django 5.2.5 on 2025-08-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название уровня')),
                ('code', models.CharField(help_text='Например: A1, B2, C1', max_length=10, unique=True, verbose_name='Код уровня')),
                ('description', models.TextField(help_text='Что студент должен уметь на этом уровне', verbose_name='Описание уровня')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (от меньшего к большему)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Уровень владения языком',
                'verbose_name_plural': 'Уровни владения языком',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название языка')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код языка')),
                ('description', models.TextField(blank=True, verbose_name='Описание языка')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли язык на платформе', verbose_name='Активный')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='Популярность')),
                ('flag_icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка флага')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='courses_lan_is_acti_b64152_idx'), models.Index(fields=['popularity'], name='courses_lan_popular_0028a6_idx')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.language', verbose_name='Язык'),
        ),
    ]
