# Generated by Django 5.2.5 on 2025-08-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_student_remove_course_teacher_alter_course_students'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='language',
            name='courses_lan_popular_0028a6_idx',
        ),
        migrations.RemoveField(
            model_name='language',
            name='popularity',
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
