# Generated by Django 5.2.5 on 2025-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_language_courses_lan_popular_0028a6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ManyToManyField(null=True, related_name='courses', to='courses.level', verbose_name='Уровень'),
        ),
    ]
