# Generated by Django 5.2.5 on 2025-08-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
